#Templates
#Documentation https://www.home-assistant.io/integrations/template/
template:
  - sensor:
      - name: 'PettixS36 auto feeder: Status'
        unique_id: pettixS36 auto feeder status
        icon: mdi:cat
        state: '{{ states("input_boolean.feeder_pettixS36_pour_the_feed_automatically") }}'
        attributes:
          Weight of bowl: '{{ states("sensor.scales_cat_bowl_weight") }}'
          Feed weight: '{{ states("sensor.scales_cat_bowl_weight_food") }}'
          Availability of a bowl: '{{ states("binary_sensor.scales_cat_bowl_bowl") }}'
          Feed availability: '{{ states("binary_sensor.scales_cat_bowl_food") }}'


#Auxiliary element: Input Boolean
#https://www.home-assistant.io/integrations/input_boolean/
input_boolean:
  feeder_pettixS36_pour_the_feed_automatically:
    name: "PettixS36 auto feeder: Feed automatically"
    icon: mdi:cat


#Groups
#https://www.home-assistant.io/integrations/group/
group:
  feeder_pettixS36_info_and_menu:
    name: "PettixS36 auto feeder: Info and menu"
    icon: mdi:information-outline
    all: false
    entities:
      - button.scales_cat_bowl_restart_esp #Reboot
      - binary_sensor.scales_cat_bowl_bowl #Availability of a bowl
      - binary_sensor.scales_cat_bowl_food #Feed availability
      - number.scales_cat_bowl_set_weight_for_bowl #Specify the weight of the bowl
      - input_number.feeder_tuya_min_feed_threshold #Minimum feed threshold
      - sensor.scales_cat_bowl_weight #Weight of bowl
      - sensor.scales_cat_bowl_weight_food #Feed weight
      - sensor.scales_cat_bowl_uptime_esp #ESP uptime


#Auxiliary element: Number
#https://www.home-assistant.io/integrations/input_number
input_number:
  feeder_pettixS36_min_feed_threshold:
    name: "Minimum feed threshold"
    min: 5
    max: 30
    step: 1
    mode: slider #box
    icon: mdi:scale

  feeder_pettixS36_feed_every_n_hours:
    name: "Feed every N hours"
    min: 0
    max: 12
    step: 1
    mode: slider #box
    icon: mdi:clock-time-four-outline


#Auxiliary element: Input Boolean
#https://www.home-assistant.io/integrations/input_boolean/
input_boolean:
  feeder_pettixS36_control_panel_1:
    name: "PettixS36 auto feeder: Control panel 1"
    icon: mdi:menu

  feeder_pettixS36_control_panel_2:
    name: "PettixS36 auto feeder: Control panel 2"
    icon: mdi:menu

  feeder_pettixS36_control_panel_3:
    name: "PettixS36 auto feeder: Control panel 3"
    icon: mdi:menu

  feeder_pettixS36_control_panel_4:
    name: "PettixS36 auto feeder: Control panel 4"
    icon: mdi:menu


#Automation
automation:
  alias: 'PettixS36 auto feeder: Lovelace. Control panel'
  description: When you switch menus, the menus don't close and you have to close one and then
    and then open another. This automation will, when opening a menu, close the other menu
  trigger:
  - platform: state
    entity_id:
    - input_boolean.feeder_pettixS36_control_panel_1
    alias: Control panel 1 - open
    id: Control panel 1 - open
    to: 'on'
  - platform: state
    entity_id:
    - input_boolean.feeder_pettixS36_control_panel_2
    alias: Control panel 2 - open
    id: Control panel 2 - open
    to: 'on'
  - platform: state
    entity_id:
    - input_boolean.feeder_pettixS36_control_panel_3
    alias: Control panel 3 - open
    id: Control panel 3 - open
    to: 'on'
  - platform: state
    entity_id:
    - input_boolean.feeder_pettixS36_control_panel_4
    alias: Control panel 4 - open
    id: Control panel 4 - open
    to: 'on'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Control panel 1 - open
        alias: Control panel 1 - open
      sequence:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id:
          - input_boolean.feeder_pettixS36_control_panel_2
          - input_boolean.feeder_pettixS36_control_panel_3
          - input_boolean.feeder_pettixS36_control_panel_4
        alias: Turn off the control panel 2,3,4
    - conditions:
      - condition: trigger
        id:
        - Control panel 2 - open
        alias: Control panel 2 - open
      sequence:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id:
          - input_boolean.feeder_pettixS36_control_panel_3
          - input_boolean.feeder_pettixS36_control_panel_4
          - input_boolean.feeder_pettixS36_control_panel_1
        alias: Turn off the control panel 1,3,4
    - conditions:
      - condition: trigger
        id:
        - Control panel 3 - open
        alias: Control panel 3 - open
      sequence:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id:
          - input_boolean.feeder_pettixS36_control_panel_4
          - input_boolean.feeder_pettixS36_control_panel_1
          - input_boolean.feeder_pettixS36_control_panel_2
        alias: Turn off the control panel 1,2,4
    - conditions:
      - condition: trigger
        id:
        - Control panel 4 - open
        alias: Control panel 4 - open
      sequence:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id:
          - input_boolean.feeder_pettixS36_control_panel_1
          - input_boolean.feeder_pettixS36_control_panel_2
          - input_boolean.feeder_pettixS36_control_panel_3
        alias: Turn off the control panel 1,2,3
  mode: single