#Шаблоны
#Документация https://www.home-assistant.io/integrations/template/
template:
      - name: 'Автокормушка Pettix S36: Статусы'
        unique_id: feeder pettix s36 status
        icon: mdi:cat
        state: '{{ states("input_boolean.feeder_pettix_s36_pour_the_feed_automatically") }}'
        attributes:
          Вес миски: '{{ states("sensor.feeder_pettix_s36_weight") }}'
          Вес корма: '{{ states("sensor.feeder_pettix_s36_weight_food") }}'
          Наличие миски: '{{ states("binary_sensor.feeder_pettix_s36_bowl") }}'
          Наличие корма: '{{ states("binary_sensor.feeder_pettix_s36_food") }}'


#Вспомогательный элемент: Input Boolean
#https://www.home-assistant.io/integrations/input_boolean/
input_boolean:
  feeder_pettix_s36_pour_the_feed_automatically:
    name: "Автокормушка Pettix S36: Сыпать корм автоматически"
    icon: mdi:cat

#Группы
#https://www.home-assistant.io/integrations/group/
group:
  feeder_pettix_s36_info_and_menu:
    name: "Автокормушка Pettix S36: Инфо и меню"
    icon: mdi:information-outline
    all: false
    entities:
      - button.scales_cat_bowl_restart_esp #Перезагрузить
      - binary_sensor.scales_cat_bowl_bowl #Наличие миски
      - binary_sensor.scales_cat_bowl_food #Наличие корма
      - number.scales_cat_bowl_set_weight_for_bowl #Указать вес миски
      - input_number.feeder_pettix_s36_min_feed_threshold #Минимальный порог корма
      - sensor.scales_cat_bowl_weight #Вес миски
      - sensor.scales_cat_bowl_weight_food #Вес корма
      - sensor.scales_cat_bowl_uptime_esp #Время бесперебойной работы ESP

#Вспомогательный элемент: Число
#https://www.home-assistant.io/integrations/input_number
input_number:
  feeder_pettix_s36_min_feed_threshold:
    name: "Минимальный порог корма"
    min: 5
    max: 30
    step: 1
    mode: slider #box
    icon: mdi:scale

  feeder_pettix_s36_feed_every_n_hours:
    name: "Кормить каждые N часов"
    min: 0
    max: 12
    step: 1
    mode: slider #box
    icon: mdi:clock-time-four-outline



#Вспомогательный элемент: Input Boolean
#https://www.home-assistant.io/integrations/input_boolean/
input_boolean:
  feeder_pettix_s36_control_panel_1:
    name: "Автокормушка Pettix S36: Панель управления 1"
    icon: mdi:menu

  feeder_pettix_s36_control_panel_2:
    name: "Автокормушка Pettix S36: Панель управления 2"
    icon: mdi:menu

  feeder_pettix_s36_control_panel_3:
    name: "Автокормушка Pettix S36: Панель управления 3"
    icon: mdi:menu

  feeder_pettix_s36_control_panel_4:
    name: "Автокормушка Pettix S36: Панель управления 4"
    icon: mdi:menu



#Автоматизация
automation:
  alias: 'Автокормушка Pettix S36: Lovelace. Панель управления'
  description: При переключении меню не закрываются и нужно закрыть одно, а потом
    открыть другое. Эта автоматизация будет при открытии меню, закрывать другое меню
  trigger:
  - platform: state
    entity_id:
    - input_boolean.feeder_pettix_s36_control_panel_1
    alias: Панель управления 1 - открыто
    id: Панель управления 1 - открыто
    to: 'on'
  - platform: state
    entity_id:
    - input_boolean.feeder_pettix_s36_control_panel_2
    alias: Панель управления 2 - открыто
    id: Панель управления 2 - открыто
    to: 'on'
  - platform: state
    entity_id:
    - input_boolean.feeder_pettix_s36_control_panel_3
    alias: Панель управления 3 - открыто
    id: Панель управления 3 - открыто
    to: 'on'
  - platform: state
    entity_id:
    - input_boolean.feeder_pettix_s36_control_panel_4
    alias: Панель управления 4 - открыто
    id: Панель управления 4 - открыто
    to: 'on'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Панель управления 1 - открыто
        alias: Панель управления 1 - открыто
      sequence:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id:
          - input_boolean.feeder_pettix_s36_control_panel_2
          - input_boolean.feeder_pettix_s36_control_panel_3
          - input_boolean.feeder_pettix_s36_control_panel_4
        alias: Выключить панель управления 2,3,4
    - conditions:
      - condition: trigger
        id:
        - Панель управления 2 - открыто
        alias: Панель управления 2 - открыто
      sequence:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id:
          - input_boolean.feeder_pettix_s36_control_panel_3
          - input_boolean.feeder_pettix_s36_control_panel_4
          - input_boolean.feeder_pettix_s36_control_panel_1
        alias: Выключить панель управления 1,3,4
    - conditions:
      - condition: trigger
        id:
        - Панель управления 3 - открыто
        alias: Панель управления 3 - открыто
      sequence:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id:
          - input_boolean.feeder_pettix_s36_control_panel_4
          - input_boolean.feeder_pettix_s36_control_panel_1
          - input_boolean.feeder_pettix_s36_control_panel_2
        alias: Выключить панель управления 1,2,4
    - conditions:
      - condition: trigger
        id:
        - Панель управления 4 - открыто
        alias: Панель управления 4 - открыто
      sequence:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id:
          - input_boolean.feeder_pettix_s36_control_panel_1
          - input_boolean.feeder_pettix_s36_control_panel_2
          - input_boolean.feeder_pettix_s36_control_panel_3
        alias: Выключить панель управления 1,2,3
  mode: single